### ISSUE TITLE
Ошибка при попытке запустить сайт

### ISSUE THREAD

**Issue by zog3nz** [RangeMC/website#1]
TypeError: Cannot read property 'trim' of undefined
    at Object.login (C:\site\node_modules\nodeactyl\client\index.js:26:14)
    at Object.<anonymous> (C:\site\website-master\index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by alexeylesin** [comment]
Необходимо переименовать файл .env.example в .env и заполнить все необходимые данные.
